# HOS04 - Section 2: NumPy - Arrays

In [2]:
import numpy as np

In [5]:
# create rank 1 dim array
arr = np.array([1, 2, 3])
print(type(arr))             # outputs <class 'numpy.ndarray'>
print(arr.dtype)             # outputs int64
print(arr.shape)             # outputs (3,)
print(arr[0], arr[1], arr[2])# outputs 1 2 3
arr[2] = 4                   # change last element to 4
print(arr)                   # outputs [1 2 4]

<class 'numpy.ndarray'>
int32
(3,)
1 2 3
[1 2 4]


In [6]:
# create rank 2 array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2.shape)            # outputs (2, 3)
print(arr2[0, 0], arr2[0, 1], arr2[1, 0])  # outputs 1 2 4
print(arr2[-1])              # outputs last element [4 5 6]

(2, 3)
1 2 4
[4 5 6]


In [7]:
# create an array of zeros with 2 dim and size of 2 each
zero = np.zeros((2, 2))
print(zero) 

[[0. 0.]
 [0. 0.]]


In [8]:
# create an array of ones with 1 dim and size of 2 each
one = np.ones((1, 2))
print(one)  

[[1. 1.]]


In [9]:
# create a 2-D array with 1 on diagonal and 0 on others
diag = np.eye(3)              # number of rows
print(diag) 

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [10]:
# diag starts at index 1
diag = np.eye(4, k=1)
print(diag) 

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]


In [11]:
# Create an array with random values
rand = np.random.random((2, 2))
print(rand)

[[0.03459587 0.37743226]
 [0.66850324 0.77124335]]


In [12]:
# Array indexing
arr = np.arange(10)                  # generate array [0 1 2 3 4 5 6 7 8 9]
print(arr[0:8:2])                    # every two number from 0 up to but not include 8

[0 2 4 6]


In [13]:
# create rank 2 with shape (3, 4) array
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(arr[:2, :2])  

[[1 2]
 [5 6]]


In [14]:
# Integer indexing
arr = np.array([[1, 2], [3, 4], [5, 6]])
print(arr[[0, 1, 2], [0, 1, 1]])  

[1 4 6]
