# DS623 – PE05 – Eigendecomposition
Topic: [Manual] Eigenvalues, Eigenvectors, Matrix Diagonalization and Power  
Student: Verónica Elze

In [1]:
import numpy as np
import time

## Step 1: Define matrix A

In [2]:
A = np.array([[-4, -3], [1, 0]])

## Step 2: Manually solve the characteristic polynomial
det(A - λI) = 0 => find eigenvalues  
A - λI = [[-4 - λ, -3], [1, -λ]]  
determinant: (-4 - λ)(-λ) - (-3)(1) = λ² + 4λ + 3 = 0

In [3]:
coeffs = [1, 4, 3]  # λ² + 4λ + 3  
eigenvalues = np.roots(coeffs)  
print("Eigenvalues (solved manually):", eigenvalues)

Eigenvalues (solved manually): [-3. -1.]


## Step 3: Manually solve (A - λI)v = 0 for each eigenvalue

In [4]:
eigenvectors = []

for λ in eigenvalues:
    A_minus_lambda_I = A - λ * np.identity(2)

    # Use reduced row echelon logic to find null space (eigenvector)
    # We'll pick one free variable = 1 to form a valid non-zero eigenvector
    # Solve A_minus_lambda_I @ v = 0
    # Use np.linalg.svd to get null space if desired, or solve manually
    # For simplicity, solve (A - λI)v = 0 using 1 equation
    
    # Extract rows
    row1 = A_minus_lambda_I[0]
    
    # Solve row1[0]*x + row1[1]*y = 0 → pick x = 1, solve for y
    if abs(row1[1]) > 1e-10:
        x = 1
        y = -row1[0] / row1[1]
    else:
        y = 1
        x = -row1[1] / row1[0]
        
    vec = np.array([x, y])
    # Normalize for consistency
    vec = vec / np.linalg.norm(vec)
    eigenvectors.append(vec)

## Step 4: Manually form matrix P and D

In [5]:
P = np.column_stack(eigenvectors)  
D = np.diag(eigenvalues)  
P_inv = np.linalg.inv(P)

print("\nEigenvectors (calculated manually, normalized):")  
print(P)


Eigenvectors (calculated manually, normalized):
[[ 0.9486833   0.70710678]
 [-0.31622777 -0.70710678]]


## Step 5: Manually verify A = P D P⁻¹

In [6]:
A_reconstructed = P @ D @ P_inv
print("\nReconstructed A (P D P⁻¹):")
print(A_reconstructed)

print("\nVerification (A - P D P⁻¹):")
print(np.round(A - A_reconstructed, decimals=10))


Reconstructed A (P D P⁻¹):
[[-4.00000000e+00 -3.00000000e+00]
 [ 1.00000000e+00 -1.78135732e-16]]

Verification (A - P D P⁻¹):
[[ 0. -0.]
 [ 0.  0.]]


OpenAI. (2025). ChatGPT’s assistance with eigendecomposition [Large language model]. https://openai.com/chatgpt