# DS623 – PE05 – Eigendecomposition
Topic: Eigenvalues, Eigenvectors, Matrix Diagonalization and Power  
Student: Verónica Elze

In [1]:
import numpy as np
import time

## Step 1: Input matrix A

In [2]:
A = np.array([[-4, -3], [1, 0]])
print("Matrix A:\n", A)

Matrix A:
 [[-4 -3]
 [ 1  0]]


## Step 2: Calculate eigenvalues and eigenvectors

In [3]:
eigenvalues, eigenvectors = np.linalg.eig(A)

## Step 3: Form matrix P from eigenvectors (columns) and diagonal matrix D from eigenvalues

In [4]:
P = eigenvectors
D = np.diag(eigenvalues)
P_inv = np.linalg.inv(P)

In [5]:
print("\nEigenvalues:")
print(eigenvalues)


Eigenvalues:
[-3. -1.]


In [6]:
print("\nEigenvectors (columns of matrix P):")
print(P)


Eigenvectors (columns of matrix P):
[[-0.9486833   0.70710678]
 [ 0.31622777 -0.70710678]]


## Step 4: Verification: A = P D P⁻¹

In [7]:
A_reconstructed = P @ D @ P_inv

In [8]:
print("\nReconstructed A (PDP⁻¹):")
print(A_reconstructed)


Reconstructed A (PDP⁻¹):
[[-4.00000000e+00 -3.00000000e+00]
 [ 1.00000000e+00 -4.80650139e-17]]


In [9]:
print("\nVerification (A - PDP⁻¹):")
print(np.round(A - A_reconstructed, decimals=10))  # Should be near-zero matrix


Verification (A - PDP⁻¹):
[[0. 0.]
 [0. 0.]]


## Step 5 (Optional): Compare computing A^1000 vs P D^1000 P^-1

In [10]:
exp = 1000
A_pow = np.linalg.matrix_power(A, exp)
D_pow = np.linalg.matrix_power(D, exp)
A_diag_pow = P @ D_pow @ P_inv

c:\Users\MissV\miniconda3\Lib\site-packages\numpy\linalg\linalg.py:680: RuntimeWarning: overflow encountered in matmul
  result = z if result is None else fmatmul(result, z)


In [11]:
print(f"\nA^{exp} (direct):")
print(A_pow)


A^1000 (direct):
[[-1114339151 -1114339152]
 [  371446384   371446385]]


In [12]:
print(f"\nA^{exp} (via diagonalization):")
print(np.round(A_diag_pow).astype(int))  # Rounded and converted for clean display


A^1000 (via diagonalization):
[[-2147483648 -2147483648]
 [-2147483648 -2147483648]]


C:\Users\MissV\AppData\Local\Temp\ipykernel_22604\366381188.py:2: RuntimeWarning: invalid value encountered in cast
  print(np.round(A_diag_pow).astype(int))  # Rounded and converted for clean display


OpenAI. (2025). ChatGPT’s assistance with eigendecomposition [Large language model]. https://openai.com/chatgpt